spring:
  application:
    name: helloTurbine
    
server:
  port: 8083
  
address:
  local: true
  
turbine:
  aggregator:
    clusterConfig: HELLOSERVICE,SEARCH-SERVICE
  appConfig: HELLOSERVICE,SEARCH-SERVICE
  
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      #defaultZone: http://52.86.121.106:8761/eureka/
      defaultZone: http://ec2-52-86-121-106.compute-1.amazonaws.com:8761/eureka/
      #defaultZone: http://ec2-52-207-143-205.compute-1.amazonaws.com:8761/eureka/

logging:
  level:
    root: INFO
#    com.netflix.hystrix.AbstractCommand: TRACE